### ISSUE TITLE
a question

### ISSUE THREAD

**Issue by Arkanic** [Gwitr/OMORI-Android#1]
What does the APK file do? does it just host/webview the files, or does it have more functionality?
I'm trying to get the game to run in the browser, and am just wondering

Thanks

**Comment by Gwitr** [comment]
The APK file just contains a WebView that lanuches browser_index.html and a few buttons. With some modification you should be able to get this running in a browser.

**Comment by Arkanic** [comment]
> The APK file just contains a WebView that lanuches browser_index.html and a few buttons. With some modification you should be able to get this running in a browser.

thanks.

**Comment by Arkanic** [comment]
Sorry to bother you again
I've reached a point where the game tries to decrypt the .OMORI files (using aes, with window.nw.App.argv as the key), but that variable is "--" rather than the steam key. Is there any way to obtain the steam key from the game files?

Thanks

**Comment by Gwitr** [comment]
Hello!
Sorry, I can't tell you how to obtain the key (npt sure how legal it is), OMORI discord might help tho. Note that (figured this out after making the instructions

**Comment by Gwitr** [comment]
i accidentally presaed "close with comment" hold on

**Comment by Gwitr** [comment]
(cont.)  ) the 1.0.0 version of the game doesn't require the key to be passed at all.

**Comment by Gwitr** [comment]
(Sorry for the 4 comments! I'm typing on a phone)

**Comment by Arkanic** [comment]
> (cont.) ) the 1.0.0 version of the game doesn't require the key to be passed at all.

strange. I must have a different version then.
Thanks.
